import java.io.*;
import java.util.*;
public class _11195_Another_n_Queen_Problem{
	public static void main(String[] args) throws NumberFormatException, IOException {
		BufferedReader br= new BufferedReader(new InputStreamReader (System.in));
		PrintWriter pr= new PrintWriter ( new BufferedWriter( new  OutputStreamWriter (System.out)) );
		int t=1;
		while(true){
			int n = Integer.parseInt(br.readLine());
			if(n==0)break;
			//String M[]= new String[n];
            //for (int i = 0; i < n; i++)M[i]=leer.next();
			int DD = 0,DI=0;
			int cant[]= new int [n];
			int  x=0,c=0;
			LinkedList<Integer> P= new LinkedList<Integer>();
			int F[]= new int[n];
			for (int i = 0; i <n; i++) P.add(i);
			boolean q=true;
			while(true){if(q){cant[x]=n-x;q=false;}
			int y=0,dd=0,di=0;
				while(cant[x]>0){
				    y= P.remove(); dd=1<<(x-y+n-1);di=1<<(x+y);
					if(//!M[y].charAt(x)=='.'&&   
							(dd&DD)!=dd && (di&DI)!=di){DD=DD|dd;DI=DI|di;
					F[x]=y;break;
					}else {P.add(y);cant[x]--;}
				}
				if(x==n-1&&cant[x]==1){c++; DD=DD&~dd; DI=DI&~di; P.add(y);cant[x]=0;
				}
                if(cant[x]==0){x--;if(x>=0){y=F[x]; DD=DD&~(1<<(x-y+n-1)); DI=DI&~(1<<(x+y)); P.add(y);cant[x]--;}else break;}
				else{q=true;x++;}
			}
			pr.println("Case "+t+": "+c);t++;
		}
		pr.close();
	}
/*	public static class Nodo {
		int v; Nodo sig;
		public Nodo(int y){v=y;sig=null;}
	}
	public static class Lista{
		Nodo ini,fin;
		public Lista(){ini=null;fin=null;}
		public void add(int y){
			Nodo aux = new Nodo(y);
			if(ini==null)ini=aux;
			else fin.sig=aux;
			fin=aux;
		}
		public int remove(){
			int x=ini.v;
			if(ini==fin)ini=fin=null;else ini=ini.sig;
			return x;
		}
	}*/
}

/*

4
5
6
7
8
9
10
11
12
13
14
15
0

8
........
........
........
........
........
........
........
........
4
.*..
....
....
....
15
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
0
14
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............
..............


*/